### ISSUE TITLE
Design Spec

### ISSUE THREAD

**Issue by josephgupkim** [Ormadont/Colmare-Academy#3]
Your project looks amazing as it's nearly identical to the design spec.
Don't forget to add a viewport meta tag to your index.html file so that your media queries are applied when a change in screen size occurs.

meta name="viewport" content="width=device-width, initial-scale=1"

After adding this tag, I can confidently say that both the desktop and mobile version look as they should!

**Comment by Ormadont** [comment]
Tag added. Thank you. I hope that this help.
